// GENERATED by tools/gen_constants.py -- do not edit by hand.
//
// Tables lifted verbatim from the reference LigandMPNN implementation so that
// featurisation in the browser matches the PyTorch model bit for bit.

/** MPNN's own amino-acid ordering. Index 20 is "X" (unknown / masked). */
export const ALPHABET = "ACDEFGHIKLMNPQRSTVWYX";

/** Amino acid one-letter code -> MPNN index. */
export const AA_TO_INT = Object.fromEntries(
  [...ALPHABET].map((aa, i) => [aa, i]),
);

/** Three-letter residue name -> one-letter code. Anything else becomes "X". */
export const THREE_TO_ONE = {
  ALA: "A", ARG: "R", ASN: "N", ASP: "D", CYS: "C", GLN: "Q", GLU: "E",
  GLY: "G", HIS: "H", ILE: "I", LEU: "L", LYS: "K", MET: "M", PHE: "F",
  PRO: "P", SER: "S", THR: "T", TRP: "W", TYR: "Y", VAL: "V",
};

/**
 * Element symbol (upper case) -> atom type index used by LigandMPNN.
 * Index 0 is reserved for "unrecognised"; hydrogen (1) is dropped from the
 * ligand context by the reference featuriser.
 */
export const ELEMENT_TO_INT = {
  H: 1,
  HE: 2,
  LI: 3,
  BE: 4,
  B: 5,
  C: 6,
  N: 7,
  O: 8,
  F: 9,
  NE: 10,
  NA: 11,
  MG: 12,
  AL: 13,
  SI: 14,
  P: 15,
  S: 16,
  CL: 17,
  AR: 18,
  K: 19,
  CA: 20,
  SC: 21,
  TI: 22,
  V: 23,
  CR: 24,
  MN: 25,
  FE: 26,
  CO: 27,
  NI: 28,
  CU: 29,
  ZN: 30,
  GA: 31,
  GE: 32,
  AS: 33,
  SE: 34,
  BR: 35,
  KR: 36,
  RB: 37,
  SR: 38,
  Y: 39,
  ZR: 40,
  NB: 41,
  MB: 42,
  TC: 43,
  RU: 44,
  RH: 45,
  PD: 46,
  AG: 47,
  CD: 48,
  IN: 49,
  SN: 50,
  SB: 51,
  TE: 52,
  I: 53,
  XE: 54,
  CS: 55,
  BA: 56,
  LA: 57,
  CE: 58,
  PR: 59,
  ND: 60,
  PM: 61,
  SM: 62,
  EU: 63,
  GD: 64,
  TB: 65,
  DY: 66,
  HO: 67,
  ER: 68,
  TM: 69,
  YB: 70,
  LU: 71,
  HF: 72,
  TA: 73,
  W: 74,
  RE: 75,
  OS: 76,
  IR: 77,
  PT: 78,
  AU: 79,
  HG: 80,
  TL: 81,
  PB: 82,
  BI: 83,
  PO: 84,
  AT: 85,
  RN: 86,
  FR: 87,
  RA: 88,
  AC: 89,
  TH: 90,
  PA: 91,
  U: 92,
  NP: 93,
  PU: 94,
  AM: 95,
  CM: 96,
  BK: 97,
  CF: 98,
  ES: 99,
  FM: 100,
  MD: 101,
  NO: 102,
  LR: 103,
  RF: 104,
  DB: 105,
  SG: 106,
  BH: 107,
  HS: 108,
  MT: 109,
  DS: 110,
  RG: 111,
  CN: 112,
  "UUT": 113,
  FL: 114,
  "UUP": 115,
  LV: 116,
  "UUS": 117,
  "UUO": 118,
};

/** Group number for each atom type index, 0..118. */
export const ATOM_GROUP = new Int32Array([
  0, 1, 18, 1, 2, 13, 14, 15, 16, 17, 18, 1, 2, 13, 14, 15, 16, 17, 18, 1, 2, 3, 4, 5, 6, 7, 8, 9,
  10, 11, 12, 13, 14, 15, 16, 17, 18, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17,
  18, 1, 2, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15,
  16, 17, 18, 1, 2, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13,
  14, 15, 16, 17, 18
]);

/** Period number for each atom type index, 0..118. */
export const ATOM_PERIOD = new Int32Array([
  0, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 3, 3, 3, 3, 3, 3, 3, 3, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4,
  4, 4, 4, 4, 4, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 6, 6, 6, 6, 6, 6, 6, 6, 6,
  6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 7, 7, 7, 7, 7, 7, 7, 7, 7,
  7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7
]);

/** Element of each of the 32 sidechain slots in the 37-atom representation. */
export const SIDE_CHAIN_ATOM_TYPES = new Int32Array([
  6, 6, 6, 8, 8, 16, 6, 6, 6, 7, 7, 8, 8, 16, 6, 6, 6, 6, 7, 7, 7, 8, 8, 6, 7, 7, 8, 6, 6, 6, 7, 8
]);

/**
 * PDB atom name of each slot in the 37-atom representation, in the reference's
 * `atom_order`. Slots 0-4 are the backbone plus C-beta; 5-36 are the side-chain
 * atoms whose elements SIDE_CHAIN_ATOM_TYPES lists, in the same order.
 */
export const ATOM37 = [
  "N", "CA", "C", "CB", "O", "CG", "CG1", "CG2", "OG", "OG1", "SG", "CD", "CD1", "CD2", "ND1",
  "ND2", "OD1", "OD2", "SD", "CE", "CE1", "CE2", "CE3", "NE", "NE1", "NE2", "OE1", "OE2", "CH2",
  "NH1", "NH2", "OH", "CZ", "CZ2", "CZ3", "NZ", "OXT"
];

/** Where the side-chain slots start in ATOM37. */
export const SIDE_CHAIN_START = 5;

/** Widths of the one-hot atom-type encoding: type, group, period. */
export const ATOM_TYPE_ONEHOT = { type: 120, group: 19, period: 8, total: 147 };

/** Virtual C-beta is placed from N/CA/C with these fixed coefficients. */
export const CB_COEFF = { a: -0.58273431, b: 0.56802827, c: -0.54067466 };

/** Radial basis expansion used for every distance feature. */
export const RBF = { min: 2.0, max: 22.0, count: 16 };

/** Relative-position encoding clamps |i - j| to this many residues. */
export const MAX_RELATIVE_FEATURE = 32;

/** Messages are summed over neighbours and divided by this constant. */
export const MESSAGE_SCALE = 30;
