#!/usr/bin/env python3
"""Emit mpnn/constants.js from the reference LigandMPNN tables.

The periodic-table and element lists are long literals in LigandMPNN's
data_utils.py / model_utils.py. Transcribing them by hand is a good way to
introduce a silent off-by-one, so we parse them out of the reference source and
generate the JS instead.

    python tools/gen_constants.py --ref <path to ligandmpnn package> --out mpnn/constants.js
"""

import argparse
import ast
import pathlib
import re
import textwrap


def literal_after(src: str, pattern: str) -> object:
    """Parse the first bracketed literal following `pattern`."""
    m = re.search(pattern, src, re.M | re.S)
    if not m:
        raise ValueError(f"pattern not found: {pattern}")
    start = src.index("[", m.end() - 1 if src[m.end() - 1] == "[" else m.end())
    depth, i = 0, start
    while True:
        if src[i] == "[":
            depth += 1
        elif src[i] == "]":
            depth -= 1
            if depth == 0:
                break
        i += 1
    return ast.literal_eval(src[start:i + 1])


def js_array(values, per_line=24, indent="  ") -> str:
    body = ", ".join(str(v) for v in values)
    return "\n".join(indent + line for line in textwrap.wrap(body, 96))


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--ref", required=True, type=pathlib.Path)
    ap.add_argument("--out", required=True, type=pathlib.Path)
    args = ap.parse_args()

    data_utils = (args.ref / "utils" / "data_utils.py").read_text()
    model_utils = (args.ref / "utils" / "model_utils.py").read_text()

    element_list = [e.upper() for e in literal_after(data_utils, r"^element_list = \[")]
    periodic = literal_after(model_utils, r"self\.periodic_table_features = torch\.tensor\(\s*\[")
    side_chain_atom_types = literal_after(
        model_utils, r"self\.side_chain_atom_types = torch\.tensor\(\s*\[")

    # `atom_order` is a dict rather than a list, so pull the names out in
    # slot order. Slots 5..36 are the side-chain atoms the context feature uses,
    # and their elements have to line up with side_chain_atom_types.
    atom_order_src = re.search(r"atom_order = \{(.*?)\n    \}", data_utils, re.S).group(1)
    atom_order = dict(re.findall(r'"([A-Z0-9]+)":\s*(\d+)', atom_order_src))
    atom37 = [None] * 37
    for name, slot in atom_order.items():
        atom37[int(slot)] = name
    assert all(atom37), "atom_order does not cover all 37 slots"
    element_of = {"C": 6, "N": 7, "O": 8, "S": 16}
    for slot, want in enumerate(side_chain_atom_types, start=5):
        got = element_of[atom37[slot][0]]
        assert got == want, f"slot {slot} ({atom37[slot]}) is {got}, table says {want}"

    assert len(periodic) == 3 and len(periodic[0]) == 119, "unexpected periodic table shape"
    groups, periods = periodic[1], periodic[2]

    # element_dict maps symbol -> index starting at 1 (0 means "unknown").
    pairs = ",\n".join(f'  {sym}: {i}' if sym.isalpha() and sym.isupper() and len(sym) <= 2
                       else f'  "{sym}": {i}'
                       for i, sym in enumerate(element_list, start=1))

    out = f"""// GENERATED by tools/gen_constants.py -- do not edit by hand.
//
// Tables lifted verbatim from the reference LigandMPNN implementation so that
// featurisation in the browser matches the PyTorch model bit for bit.

/** MPNN's own amino-acid ordering. Index 20 is "X" (unknown / masked). */
export const ALPHABET = "ACDEFGHIKLMNPQRSTVWYX";

/** Amino acid one-letter code -> MPNN index. */
export const AA_TO_INT = Object.fromEntries(
  [...ALPHABET].map((aa, i) => [aa, i]),
);

/** Three-letter residue name -> one-letter code. Anything else becomes "X". */
export const THREE_TO_ONE = {{
  ALA: "A", ARG: "R", ASN: "N", ASP: "D", CYS: "C", GLN: "Q", GLU: "E",
  GLY: "G", HIS: "H", ILE: "I", LEU: "L", LYS: "K", MET: "M", PHE: "F",
  PRO: "P", SER: "S", THR: "T", TRP: "W", TYR: "Y", VAL: "V",
}};

/**
 * Element symbol (upper case) -> atom type index used by LigandMPNN.
 * Index 0 is reserved for "unrecognised"; hydrogen (1) is dropped from the
 * ligand context by the reference featuriser.
 */
export const ELEMENT_TO_INT = {{
{pairs},
}};

/** Group number for each atom type index, 0..118. */
export const ATOM_GROUP = new Int32Array([
{js_array(groups)}
]);

/** Period number for each atom type index, 0..118. */
export const ATOM_PERIOD = new Int32Array([
{js_array(periods)}
]);

/** Element of each of the 32 sidechain slots in the 37-atom representation. */
export const SIDE_CHAIN_ATOM_TYPES = new Int32Array([
{js_array(side_chain_atom_types)}
]);

/**
 * PDB atom name of each slot in the 37-atom representation, in the reference's
 * `atom_order`. Slots 0-4 are the backbone plus C-beta; 5-36 are the side-chain
 * atoms whose elements SIDE_CHAIN_ATOM_TYPES lists, in the same order.
 */
export const ATOM37 = [
{js_array([f'"{n}"' for n in atom37])}
];

/** Where the side-chain slots start in ATOM37. */
export const SIDE_CHAIN_START = 5;

/** Widths of the one-hot atom-type encoding: type, group, period. */
export const ATOM_TYPE_ONEHOT = {{ type: 120, group: 19, period: 8, total: 147 }};

/** Virtual C-beta is placed from N/CA/C with these fixed coefficients. */
export const CB_COEFF = {{ a: -0.58273431, b: 0.56802827, c: -0.54067466 }};

/** Radial basis expansion used for every distance feature. */
export const RBF = {{ min: 2.0, max: 22.0, count: 16 }};

/** Relative-position encoding clamps |i - j| to this many residues. */
export const MAX_RELATIVE_FEATURE = 32;

/** Messages are summed over neighbours and divided by this constant. */
export const MESSAGE_SCALE = 30;
"""
    args.out.parent.mkdir(parents=True, exist_ok=True)
    args.out.write_text(out)
    print(f"wrote {args.out} ({len(element_list)} elements, "
          f"{len(side_chain_atom_types)} sidechain slots)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
